# Page settings

baseURL = "https://fanny-r.github.io/"
languageCode = "en"
title = "Fanny Rottee - Software Engineer"
theme = "hugo-devresume-theme"
googleAnalytics = ""



[params]
    author = "Fanny Rottee"
    description = "As a developer I want to produce a code tested, maintenable and well organized. I have learned a lot since I started developing and I want to find a team where I would be able to continue to progress."


    primaryColor = "#489DA0"
    textPrimaryColor = "#2D1828"


    [params.profile]
        enable = true
        name = "Fanny Rottee"
        tagline = "Software Engineer"
        # avatar = "avatar.png"


    [params.contact]
        enable = true
        location = "Lyon (France)"

        [[params.contact.list]]
        # icon = "fas fa-phone-square"
        # url = "tel:#"
        # text = "+33 6 31 75 92 20"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "fanny.rottee@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "https://fanny-r.github.io/"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "PHP: Symfony (1/2/3), PHPUnit, Behat"
        [[params.skills.list.items]]
        details = "Ruby: Rails, RSpec, Sidekiq"
        [[params.skills.list.items]]
        details = "MySQL, Elasticsearch, Redis"
        [[params.skills.list.items]]
        details = "Git, Docker, RabbitMq"
        [[params.skills.list.items]]
        details = "Object-oriented design"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"


    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BSc in Computer Science"
        university = "Université Lyon 1"
        dates = "2015 - 2017"
        [[params.education.list]]
        degree = "BSc in Library and Information Science - Digital Information Management"
        university = "Université Grenoble Alpes"
        dates = "2010-2012"
        [[params.education.list]]
        degree = "BSc in Economics and Management"
        university = "Université Grenoble Alpes - Universität Leipzig (Germany)"
        dates = "2007 - 2010"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "French"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Fluent"
        [[params.languages.list]]
        name = "German"
        level = "Intermediate"
        [[params.languages.list]]
        name = "Spanish"
        level = "Intermediate - Self-Taught"


    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Hiking"
        [[params.interests.list]]
        name = "Reading"
        [[params.interests.list]]
        name = "Travelling"
        [[params.interests.list]]
        name = "Eating"


    [params.summary]
        enable = true
        text = "As a developer I want to produce a code tested, maintenable and well organized. I have learned a lot since I started developing and I want to find a team where I would be able to share my knowledge while continuing to progress."


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2016 - Present"
        company = "Vivlio"
        details = "My training and previous experiences are helping me to grasp the complexity of the work as a software engineer in Vivlio, a french start-up that aims to be a European alternative in the digital book industry. I am working in a small agile team where I am involved in the whole development life cycle, from design to maintenance, including of course development, but also testing, deployment and monitoring. We are doing systematic code reviews and pair programming on a regular basis and I occasionally supervised and mentored newcomers. My missions involve working in conjunction with after-sales service, editorial and marketing teams to best meet the needs of our clients and customers. I also had the opportunity to take more responsability by being the technical referent of one of our project."

        [[params.experience.list]]
        title = "Software Engineer (3 months Internship)"
        dates = "2016"
        company = "Aberdeen's Robert Gordon University (Scotland)"
        details = "As an intern my mission was to develop (from scratch) a prototype Android and Android wear app as part of a project that intended to develop a support system for people living with low back pain. The app was collecting data from the sensors present on a smartwatch, sending it on a mobile phone where the data was analysed in order to predict the activity done by the user, and then the result was displayed. The most important part was to implement the activity recognition system developped by a research  fellow. I worked alone and independently, however, as I was creating a prototype destined to other people, I made sure that to have a clean and well documented code."
        [[params.experience.list.items]]
        details = "Java Android, for mobile phone and smartwatch"
        [[params.experience.list.items]]
        details = "Librairies: OpenCV and MPAndroidChart"

        [[params.experience.list]]
        title = "Volunteering in farms in the UK"
        dates = "2014"
        company = "WWOOF"
        details = "I traveled during 6 months in the UK helping with daily tasks in farms or gardens, and living alongside my hosts. I did a lot of gardening (so much weeding), but I also was lucky enough to help in a farm during lambing time. I learned to work under pressure, sometimes alone, and to take quick decisions. More generally this time out of my comfort zone has allowed me to discover a new culture and new ways of thinking."

        [[params.experience.list]]
        title = "Various short-term jobs"
        dates = "2012 - 2015"
        company = "Decitre, Lizeo..."
        details = "I used to work as a librarian and a data-entry operator. These jobs taught me to work rigorously, within deadlines and according to instructions. However, I lacked carreer prospects, and I wanted to have the opportunity to be a driving force and not just a executor. I was eager to learn more and to do a job I would be able to progress in."


    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."


    [params.information]
        enable = true

        [[params.information.list]]
        title = "Interests"
        details = "Hiking, Reading, Travelling, Eating"


    [params.social]
        enable = false

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/username"
        title = "@username"
