# Page settings

baseURL = "https://fanny-r.github.io/"
title = "Fanny Rottée - Software Engineer"
theme = "hugo-devresume-theme-custom"
googleAnalytics = ""

defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false

[languages]
    [languages.fr]
        label = "Français"
        locale = "fr-FR"
        weight = 1

    [languages.en]
        label = "English"
        locale = "en-US"
        weight = 2



[params]
    author = "Fanny Rottée"
    description = "As an engineer I focus on problem solving, from producing quality, maintainable and well organized code to driving business initiatives. I am known to be very pragmatic and product centric. I care about my users and I want to make their life easier with my code. I want to find a team in which I would be able to share my knowledge while continuing to progress."


    primaryColor = "#50a6d8"
    textPrimaryColor = "#2D1828"


    [params.profile]
        enable = true
        name = "Fanny Rottée"
        tagline = "Software Engineer"
        # avatar = "avatar.png"


    [params.contact]
        enable = true
        location = "Lyon (France)"

        # [[params.contact.list]]
        # icon = "fas fa-phone-square"
        # url = "tel:#"
        # text = ""
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "fanny.rottee@gmail.com"
        # [[params.contact.list]]
        # icon = "fas fa-globe"
        # url = "#"
        # text = "https://fanny-r.github.io/"


    [params.skills]
        enable = true


    [params.education]
        enable = true


    [params.languages]
        enable = true


    [params.interests]
        enable = true

    [params.summary]
        enable = false


    [params.experience]
        enable = true

    [params.information]
        enable = false


    [params.social]
        enable = false

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/username"
        title = "@username"
